import { NodeGeoData } from "./node-geo-data";
import { NodeStatistics } from "./node-statistics";
import { QuorumSet } from "./quorum-set";
export declare class Node {
    protected _ip: string;
    protected _port: number;
    protected _publicKey?: string;
    protected _name?: string;
    protected _host?: string;
    protected _ledgerVersion?: string;
    protected _overlayVersion?: string;
    protected _overlayMinVersion?: string;
    protected _networkId?: string;
    protected _versionStr?: string;
    protected _quorumSet: QuorumSet;
    protected _active: boolean;
    protected _geoData: NodeGeoData;
    protected _statistics: NodeStatistics;
    protected _dateDiscovered: Date;
    protected _dateUpdated: Date;
    protected _overLoaded: boolean;
    constructor(ip: string, port?: number, publicKey?: string, active?: boolean, overLoaded?: boolean, quorumSet?: QuorumSet, geoData?: NodeGeoData, statistics?: NodeStatistics, dateDiscovered?: Date, dateUpdated?: Date);
    readonly displayName: string;
    active: boolean;
    overLoaded: boolean;
    readonly key: string;
    ip: string;
    port: number;
    publicKey: string;
    name: string;
    host: string;
    ledgerVersion: string;
    overlayVersion: string;
    overlayMinVersion: string;
    networkId: string;
    versionStr: string;
    quorumSet: QuorumSet;
    geoData: NodeGeoData;
    statistics: NodeStatistics;
    dateDiscovered: Date;
    dateUpdated: Date;
    toJSON(): Object;
    static fromJSON(node: string | Object): Node;
}
